name: Deploy to DirectAdmin Host

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    name: 🎉 Deploy via SFTP
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
      
    - name: 📂 Sync files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        source: "./*"
        target: "/domains/yoursite.com/public_html/widget/"
        strip_components: 1
